services:
  front:
    build:
      context: . ## build Docker file location
      dockerfile: Dockerfile ## build file name
    ports:
      - '3000:3000'
    container_name: client-server
    environment:
      TZ: Asia/Seoul
    networks:
      - ubuntu_infra

  networks:
    ubuntu_infra:
      external: true
