import type { Metadata } from 'next';
import './globals.css';
import { OverlayProvider } from '@/hooks/use-overlay';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="bg-custom-black-with-opacity">
        <OverlayProvider>
          <div className="w-[36rem] min-h-screen bg-custom-white mx-auto pb-[10rem]">
            {children}
          </div>
        </OverlayProvider>
      </body>
    </html>
  );
}
