import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="bg-custom-black-with-opacity">
        <div className="w-[36rem] min-h-[64rem] bg-custom-white mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
