import type { Metadata } from 'next';
import './globals.css';
import dynamic from 'next/dynamic';
const Provider = dynamic(() => import('../app/_component/Provider'), {
  ssr: false,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="bg-custom-black-with-opacity">
        <Provider>
          <div className="w-[36rem] min-h-screen bg-custom-white mx-auto">
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
